"use strict";
const test=require('node:test');
const assert=require('node:assert/strict');
const {PAIRS,ledger,uniqueOrders,orderSize,sellSize,page}=require('./multi-live');
const buy={ordId:'1',clOrdId:'ANTON1',instId:'ETH-EUR',side:'buy',accFillSz:'0.01',avgPx:'3000',fee:'-0.00001',feeCcy:'ETH',cTime:'100'};
const sell={ordId:'2',clOrdId:'ANTON2',instId:'ETH-EUR',side:'sell',accFillSz:'0.005',avgPx:'3300',fee:'-0.02',feeCcy:'EUR',cTime:'200'};
test('only three EUR pairs; dashboard does not imply 200 EUR actual balance',()=>{assert.deepEqual(PAIRS,['BTC-EUR','ETH-EUR','DOGE-EUR']);const html=page();assert.match(html,/ETH-EUR/);assert.match(html,/DOGE-EUR/);assert.match(html,/Не фактическая сумма на счёте/);});
test('order history deduplicates and fails closed if page reaches cap',()=>{assert.equal(uniqueOrders([buy],[buy]).length,1);assert.throws(()=>uniqueOrders(Array(100).fill(buy),[]),/INCOMPLETE/);assert.deepEqual(uniqueOrders([{...buy,clOrdId:'PERSONAL'}],[]),[]);});
test('position accounts for fees and cannot sell personal assets',()=>{const p=ledger([buy,sell],3300);assert.ok(p.qty>0.0049&&p.qty<0.005);assert.ok(p.pnlEur>0&&p.pnlEur<4);assert.equal(p.fills,2);assert.throws(()=>ledger([sell],3300),/EXCEEDS_TRACKED/);});
test('5 EUR source order is never inflated to exchange minimum',()=>{assert.equal(orderSize({state:'live',minSz:'0.0001',lotSz:'0.00000001'},67000,5).valid,false);assert.equal(orderSize({state:'live',minSz:'1',lotSz:'1'},0.2,5).valid,true);assert.equal(orderSize({state:'suspend',minSz:'1',lotSz:'1'},0.2,5).valid,false);assert.equal(orderSize({state:'live',minSz:'1',lotSz:'1'},0.2,6).valid,false);});
test('sell rounding is downward for whole and fractional tokens',()=>{assert.equal(sellSize(10,10,1,1),'10');assert.equal(sellSize(3.8,3.8,1,1),'3');assert.equal(sellSize(0.00231,0.00231,0.0001,0.0001),'0.0023');assert.equal(sellSize(0.0023,0.001,0.0001,0.002),null);});
