'use strict';
const http = require('node:http');
const {evaluate}=require('./scanner');
const {scan:polyScan}=require('./live-feed');
const {scan:krakenScan}=require('./kraken-spot');
const port=Number(process.env.PORT||3000);
if(!Number.isInteger(port)||port<1||port>65535)throw Error('Invalid PORT');
const send=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data));};
const demo=Object.freeze({marketId:'SYNTHETIC EXAMPLE',outcomeA:{ask:0.18,size:100},outcomeB:{ask:0.78,size:80},payout:1,feeA:0.005,feeB:0.005,settlementCost:0,minProfit:0});
const cache=new Map(),flights=new Map();
async function cached(key,fn){const old=cache.get(key);if(old&&Date.now()-old.time<60000)return old.data;if(!flights.has(key))flights.set(key,fn().then(data=>{cache.set(key,{time:Date.now(),data});return data;}).finally(()=>flights.delete(key)));return flights.get(key);}
const page=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ANTON Arbitrage PAPER</title><style>body{font:16px system-ui,sans-serif;max-width:760px;margin:24px auto;padding:0 16px;line-height:1.45;background:#101827;color:#f5f7fa}main{background:#202b3d;border-radius:18px;padding:22px}strong,a{color:#85e0b8}.warn{background:#433324;padding:12px;border-radius:9px}button{background:#85e0b8;border:0;padding:12px 18px;border-radius:8px;font-weight:bold;cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#101827;padding:16px;border-radius:10px}</style></head><body><main><h1>ANTON Arbitrage</h1><p><strong>Отдельный PAPER-сервис · бюджет расчёта максимум 100 €</strong></p><p class="warn">РЕАЛЬНЫЕ ОРДЕРА ОТКЛЮЧЕНЫ. Котировки из разных запросов не синхронны; расчёт не является исполнимым арбитражем. Германия: Polymarket нельзя использовать для открытия позиций.</p><h2>Kraken: треугольный спот-расчёт</h2><p>EUR / BTC / ETH. Учитывает предположительно по 0,8% taker-комиссии на каждую из трёх операций и ликвидность лучших уровней. Личная тарифная ставка, ограничения пар, минимальные ордера и реальное исполнение ещё не проверены.</p><button id="kraken" type="button">Получить котировки Kraken</button><pre id="krakenout">Ожидание запроса.</pre><h2>Polymarket: только справочные цены</h2><button id="poly" type="button">Получить справочные котировки</button><pre id="polyout">Торговля Polymarket из Германии недоступна.</pre><h2>Синтетический пример</h2><button id="demo" type="button">Посчитать пример</button><pre id="demoout">Вымышленные цены.</pre><p><a href="/health">Статус</a> · <a href="/kraken">Kraken JSON</a> · <a href="/markets">Polymarket JSON</a></p></main><script>async function load(url,id){const el=document.getElementById(id);el.textContent='Загрузка…';try{const r=await fetch(url);const d=await r.json();if(!r.ok)throw Error(d.error||'HTTP '+r.status);el.textContent=JSON.stringify(d,null,2)}catch(e){el.textContent='Ошибка: '+e.message}}document.getElementById('kraken').onclick=()=>load('/kraken','krakenout');document.getElementById('poly').onclick=()=>load('/markets','polyout');document.getElementById('demo').onclick=()=>load('/demo','demoout');load('/kraken','krakenout');</script></body></html>`;
const server=http.createServer((req,res)=>{
 if(req.method==='GET'&&req.url==='/health')return send(res,200,{status:'ok',mode:'PAPER',tradesEnabled:false,hardBudgetEUR:100,krakenFeedReceived:cache.has('kraken'),krakenDataTimestamp:cache.get('kraken')?.data.fetchedAt||null,polymarketTradingAllowedInGermany:false});
 if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'"});return res.end(page);}
 if(req.method==='GET'&&req.url==='/kraken'){cached('kraken',krakenScan).then(d=>send(res,200,d)).catch(e=>send(res,503,{mode:'PAPER',source:'Kraken',error:String(e.message).slice(0,140),tradesEnabled:false}));return;}
 if(req.method==='GET'&&req.url==='/markets'){cached('poly',polyScan).then(d=>send(res,200,{...d,polymarketTradingAllowedInGermany:false})).catch(e=>send(res,503,{mode:'PAPER',source:'Polymarket',error:String(e.message).slice(0,140),tradesEnabled:false}));return;}
 if(req.method==='GET'&&req.url==='/demo')return send(res,200,{synthetic:true,result:evaluate(demo)});
 if(req.method!=='POST'||req.url!=='/evaluate')return send(res,404,{error:'Not found'});
 if(req.headers['content-type']?.split(';')[0]?.trim()!=='application/json')return send(res,415,{error:'JSON required'});
 let body='';let tooLarge=false;
 req.on('data',chunk=>{body+=chunk;if(Buffer.byteLength(body)>16384&&!tooLarge){tooLarge=true;send(res,413,{error:'Payload too large'});req.destroy();}});
 req.on('end',()=>{if(tooLarge)return;try{send(res,200,{userSuppliedData:true,verified:false,result:evaluate(JSON.parse(body))});}catch(e){send(res,400,{mode:'PAPER',error:e.message});}});
});
if(require.main===module)server.listen(port,'0.0.0.0',()=>console.log(`ANTON Arbitrage PAPER on ${port}; Kraken public scan enabled, all real trading disabled`));
module.exports=server;
